version: '3.8'

services:
  react:
    image: node:16.14
    volumes:
      - "./src/react/static:/static"

  nginx:
    image: nginx:1.21
    volumes:
      - "./src/react/static:/static:ro"
      - "./src/nginx/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80"
    depends_on:
      - react
