version: '3.8'

services:
  nginx:
    volumes:
      - "./src/react/build:/frontend:ro"
      - "./src/nginx/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80"
    depends_on:
      - express
