version: '3.8'

services:
  mongo:
    image: mongo:4.4.14
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - "./data/mongo/db:/data/db"

  express:
    build:
      context: ./env/express
    env_file: ./env/express/.env
    image: inventorization/express:dev
    volumes:
      - "./src/express:/app"
    depends_on:
      - mongo

  webpack:
    build:
      context: ./env/webpack
    image: inventorization/webpack:dev
    volumes:
      - "./src/webpack:/app"
      - "./src/nginx/static:/static"

  nginx:
    image: nginx:1.21
    volumes:
      - "./src/nginx/static:/static"
      - "./src/nginx/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80"
    depends_on:
      - express
      - webpack
