version: '3.8'

services:
  react:
    build:
      context: ./env/react
    image: inventorization/react:dev
    volumes:
      - "./src/react:/app"

  nginx:
    volumes:
      - "./src/nginx/nginx.dev.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80"
      - "3000:3000"
    depends_on:
      - express
      - react
