version: '3.8'

services:
  django:
    image: inventorization/django:1.0.0
    restart: always

  nginx:
    volumes:
      - "./src/react/build:/frontend:ro"
      - "./src/nginx/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80"
    depends_on:
      - django
    restart: always
