version: '3.8'

services:
  mongo:
    image: mongo:4.4.14
    env_file: ./env/mongo/.env
    volumes:
      - "./data/mongo/db:/data/db"

  express:
    build:
      context: ./env/express
    env_file: ./env/express/.env
    image: inventorization/express
    volumes:
      - "./src/express:/app"
    depends_on:
      - mongo

  nginx:
    image: nginx:1.21
