version: '3.8'

services:
  postgres:
    image: postgres:16.2
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    env_file: ./env/postgres/.env
    volumes:
      - "./data/postgres/pgdata:/var/lib/postgresql/data/pgdata"

  django:
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      SECRET_KEY: "${DJANGO_SECRET_KEY}"
      ALLOWED_HOSTS: "${DJANGO_ALLOWED_HOSTS}"
    volumes:
      - "./src/django:/app"
    depends_on:
      - postgres

  nginx:
    image: nginx:1.21
