version: '3.8'

services:
  mongo:
    image: mongo:4.4.14
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - "./data/mongo/db:/data/db"

  express:
    image: node:16.14
    volumes:
      - "./src/express:/app"
    depends_on:
      - mongo

  webpack:
    image: node:16.14
    volumes:
      - "./src/webpack/static:/static"

  nginx:
    image: nginx:1.21
    volumes:
      - "./src/react/static:/static:ro"
      - "./src/nginx/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80"
    depends_on:
      - express
      - webpack
