export const CHANGE_SEARCH_TYPE: 'CHANGE_SEARCH_TYPE' = 'CHANGE_SEARCH_TYPE';
export const CHANGE_SEARCH_QUERY: 'CHANGE_SEARCH_QUERY' = 'CHANGE_SEARCH_QUERY';
export const GET_SEARCH_RESULTS_REQUEST_PENDING: 'GET_SEARCH_RESULTS_REQUEST_PENDING' = 'GET_SEARCH_RESULTS_REQUEST_PENDING';
export const GET_SEARCH_RESULTS_REQUEST_SUCCESS: 'GET_SEARCH_RESULTS_REQUEST_SUCCESS' = 'GET_SEARCH_RESULTS_REQUEST_SUCCESS';
export const GET_SEARCH_RESULTS_REQUEST_FAILED: 'GET_SEARCH_RESULTS_REQUEST_FAILED' = 'GET_SEARCH_RESULTS_REQUEST_FAILED';
